### ISSUE TITLE
Songs stored in SonicFlow

### ISSUE THREAD

**Issue by weikanglim** [acm-ndsu/SonicFlow#12]
Correct me if I'm wrong, but currently all songs returned from a Grooveshark search is stored in the SonicFlow database.

Would storing only user requested songs, instead of all songs returned from a search be more beneficial? That way, we are only storing relevant information from search.es

**Comment by weikanglim** [comment]
Duplicate issue raised by #10

**Comment by zeande** [comment]
One problem with that is searching by artist. The purpose for caching the data is to minimize the API calls to these services.  If a user is interested in, for example, the artist Rammstein and we only cache the song that he or she chose, then the next time they do this search, we will have to pull from the tiny song and grooveshark APIs again (time consuming) if they wish to hear a song that is different from the one they just heard.
________________________________
Von: Psychonut<mailto:notifications@github.com>
Gesendet: ‎26.‎02.‎2015 10:38
An: acm-ndsu/SonicFlow<mailto:SonicFlow@noreply.github.com>
Betreff: [SonicFlow] Songs stored in SonicFlow (#12)

Correct me if I'm wrong, but currently all songs returned from a Grooveshark search is stored in the SonicFlow database.

Would storing only user requested songs, instead of all songs returned from a search be more beneficial? That way, we are only storing relevant information from search.es

---
Reply to this email directly or view it on GitHub:
https://github.com/acm-ndsu/SonicFlow/issues/12
